### ISSUE TITLE
Overlapping partitions in DataFrames

### ISSUE THREAD

**Issue by mrocklin** [blaze/dask#223]
For resampling and sliding window operations on series we could use logic to overlap partitions slightly.  This would be analogous to [dask.array.ghost](http://dask.readthedocs.org/en/latest/ghost.html) but would overlap based on index value (e.g. overlap by 10 minutes) rather than by number of elements (e.g. overlap by 10 items).

For time series sliding window operations often only need ghosting in one direction, so that might be worth inserting.

It's still not clear to me that people have time series long enough to warrant spending time on this.  @ssanderson and I were talking about this [on gitter](https://gitter.im/ContinuumIO/dask?at=55539ca08eadf6415fb19083).

**Comment by ssanderson** [comment]
> It's still not clear to me that people have time series long enough to warrant spending time on this.

I think high-granularity financial data and/or analytics data would fall into this category.

What's less obvious to me is whether people who have time-series data this large are willing to pay the additional overhead of working with it in a richer dataframe-like format versus working with it in a format more like dask.array.

In our case, because we care about the market calendar, it's more often correct to think about trailing windows on N **bars** of data, rather than N **days** of data.  For example, a 3-day trailing window is not a very useful construct when you don't have data on weekends.

You had also mentioned that anisotropic ghosting for dask.array might produce performance wins in a distributed context.  I take it you think there are less substantial wins to be had in a single-machine context?

**Comment by mrocklin** [comment]
> I think high-granularity financial data and/or analytics data would fall into this category.

How many entries do these datasets have?  

N **bars** of data is certainly easier than N **days**.  If there isn't value to the N days case then we can happily ignore this application.

Regarding anisotropic ghosting, this significantly reduces the number of necessary communications between tasks (the graph is less tangled.)  In a single machine communication is mostly free, so we don't care about a tangled graph.  It might be that in a distributed context communication is more of an issue.  I would want someone to report that it's slow before I devoted time to anisotropic ghosting though; it's entirely possible that it's not a bottleneck.

**Comment by ssanderson** [comment]
> How many entries do these datasets have?

For something like a 10 year OHLCV dataset, minutely data will have on the order of (10 years * ~250 market days per year * ~400 minutes per day * 5 fields) = ~5 million data points per asset.  At any given time you have between 8000 and 10000 equities if you only care about the US, so that leaves you with on the order of at least 40 billion data points, which translates to 160 GB

**Comment by mrocklin** [comment]
Do you care about sliding window computations that cross securities?

**Comment by ssanderson** [comment]
> Do you care about sliding window computations that cross securities?

For the most part no.  There are use-cases for things like pairwise correlation matrices, but since there isn't really a natural order on that axis of the data, it doesn't really make sense to do rolling windows.

**Comment by mrocklin** [comment]
Then do people usually split up the 160GB into 10000 pieces, one per security?

**Comment by mrocklin** [comment]
I guess I'm trying to figure out if people want to parallelize within each time series or simply across securities.  We can support both but across securities is simpler.

**Comment by ssanderson** [comment]
We currently block our data by time, but that's partly a historical artifact, and partly for ease-of-deployment reasons: it's much easier to update the most recent data file than it is to update a file for every security.

As far as parallelization goes, I'd imagine that per-security (or per-N-securities) would be the way to go.  I think if dask supported moving-window computations, the user benefits would come more from handling nitty-gritty boundary-traversal details than from parallelization, which might be a problem you're less interested in solving.

**Comment by mrocklin** [comment]
OK, the fact that time series are often appended to on a daily basis seems like a decent reason to support moving window computations, even if not made necessary by memory constraints.

**Comment by mrocklin** [comment]
We've managed this is relevant computations by bringing together two or three neighboring dataframes and then loc-ing down.  This has proven sufficiently effective that I'm now closing this.
