### ISSUE TITLE
Spec for list literals in dasks

### ISSUE THREAD

**Issue by jcrist** [blaze/dask#421]
Painpoint I discovered while working on #408. Mildly related to #419.

Currently, list literals not surrounded by a function return iterators. This is a fairly simple fix in the codebase, but I want to get our spec straight before fixing it. Options:

```
dsk = {'a': 1,
       'b': 2,
       'case_1': ['a', 'b'],
       'case_2': (sum, ['a', 'b']),
       'case_3': (sum, [['a'], ['b']])}
```

- `case_1` currently fails. It's not clear if supporting this is a good idea or not. Many people expect this to work, but it would make including a list containing items that happen to collide with keys difficult.
- `case_2` currently works. This is fine.
- `case_3` currently fails.

A work around is to recursively wrap all literal lists in a call to list (`[1, 2, 3] -> (list, [1, 2, 3])`), but this seems like a hack. I think that `'case_3'` should definitely work, and am unsure about `'case_1'`.

Ping @mrocklin, @eriknw for advice.

**Comment by shoyer** [comment]
The distinction between tuples and other types has definitely been an annoyance to keep track of when building dask graphs manually.

I would really like something like `quasiquote` (typically used as `import dask.something.quasiquote as q`) as a simple way to identify keys that are not tasks. Then we could have a consistent rule about turning tasks into keys, even in possibly nested lists, by insisting that people use quasiquote. @mrocklin and I discussed this recently on one of his pull requests where I didn't understand what was going on (because he used `(list, [1, 2, 3])`).

**Comment by jcrist** [comment]
In my mind, we have the following distinction at the dask level:
- Value is a "task"
- Value is data

Tasks are tuples with first element as a callable, everything else is data. If it's a task, it's recursively traversed, replacing all keys with their values. If it's data, nothing is traversed. This means that `'case_1'` above should always return `['a', 'b']`, as it's a literal list of strings (data, not a task), while `case_2` and `case_3` should be traversed, replacing keys with data.

This simple *top level* distinction makes sense to me, and seems the simplest way forward. Tasks always replace, data never replaces.

**Comment by jcrist** [comment]
On further thought, that distinction above fails if the data is ever inlined, so a recursive definition is needed. Drat, I was hoping it would be that simple :/ Looks like some kind of indicator (quasiquote or whatever) is needed to indicate the difference between data and keys.

**Comment by jcrist** [comment]
Upon further thought, it seems better to only traverse lists that are arguments to a task (i.e. traverse `(foo, [a, b, c])`, but not `[a, b, c]`). Current behavior is fine. Closing.
