### ISSUE TITLE
segmentation fault with dask.dataframe.read_hdf

### ISSUE THREAD

**Issue by rabernat** [blaze/dask#760]
I continue in my quest to use dask with a large hdf file.

After learning that my original pytables-generated HDF files might not be able to be read by dask.dataframe (because dask uses subselection: pydata/pandas#11188), I tried re-generating the files using the pandas HDFStore interface. (First I had to updated pytables overcome a different bug: pydata/pandas#10672.) (Also, in the meantime, a workaround was found for reading the pytables file into dask: #747, #759.)

Anyway, now I have a pandas-generated HDF file. I can read it with pandas, but with dask I am getting a segfault.

```python
import pandas as pd
import dask.dataframe as dd
fname = '/data/scratch/rpa/global_lagrangian/run/pandas_floats.h5'
key = '/floats/trajectories'
df = pd.read_hdf(fname, key)
ddf = dd.read_hdf(fname, key)
print(len(df))
print(len(ddf))
```

The first print statement gives ``753664023``. The second generates a segfault via the ``len`` call.

I can still call ``ddf.head()`` and ``ddf.tail()``, but other more complex operations (e.g. ``groupby``) fail, presumably due to the same underlying issue.

I am using all the latest masters of dask, pandas, and pytables.

**Comment by cowlicks** [comment]
This might be hard to debug without a little more info. Could you try stepping through the computation with pdb to see where the segfault happens?

**Comment by mrocklin** [comment]
This would probably require the use of `gdb` rather than `pdb`.

I think that the right thing to do from a dask development perspective is to kick this up to pytables as an issue about thread-safety.  I suspect that if you were to make many calls like `df.read_hdf(..., start=100000*i, stop=100000*(i+1))` in different threads that this would trigger the issue without dask (this is, in fact, all that dask is doing with `read_hdf`).  I hesitate to dive into the PyTables code personally.

@rabernat are you able to produce a minimum working example of this segfault, preferably with data that we can share?  

If you just want to get things working then I suspect you could turn off threading and things would be fine (if slightly slower)

```python
import dask
dask.set_options(get=dask.async.get_sync)  # turn off threads globally
```

**Comment by mrocklin** [comment]
We could also throw in a `lock=True` keyword argument around the `pd.read_hdf` calls

**Comment by shoyer** [comment]
:+1: for `lock=True`. HDF5 does not support concurrency with threads (this is normally not an issue unless you've enabled compression or are using multiple disks), so we can either add our own lock or push the lock upstream to pytables, but in the end it will all be the same.

**Comment by mrocklin** [comment]
@rabernat can you verify that dd.read_hdf works fine in your example with a single thread?  If so then I'll go ahead and add a lock around the `pd.read_hdf` calls.

```python
import dask
dask.set_options(get=dask.async.get_sync)  # turn off threads globally
```

**Comment by rabernat** [comment]
Yes, I can verify that dd.read_hdf works with if I first call ``dask.set_options(get=dask.async.get_sync)``. (It's is quite slow though--I guess it has to read the whole dataset just figure out how many rows in the table.)

Do you still want me to develop a minimum non-working example? Or is the source of the problem (HDF5 threading issues) sufficiently clear already?
