### ISSUE TITLE
feature request for dask array

### ISSUE THREAD

**Issue by 22csnyder** [blaze/dask#789]
Hi,

I'm definitely enjoying dask.array, and I recommend it when I can. I found it useful to write one class that stored the array as an np.array when compute() was previously called and when space was available. This is useful because I'm transparently working with data that is both large and small. When it can fit in memory I'd like to take advantage of that.

Let's use daX and npX for dask and numpy arrays members respectively. A simple workaround is to modify __getattr__ to return npX if available, else daX, when you ask for member X.

Is this something that seems generally useful, or is it just me?

Chris Snyder

**Comment by mrocklin** [comment]
Hrm, interesting.  This is the sort of thing that @shoyer might also find to be useful.

I would be curious to get your feedback on a caching system somewhat similar to this currently built into the dask schedulers.  Let me write up a quick doc page.

**Comment by mrocklin** [comment]
@22csnyder I would be interested to hear your thoughts on http://dask.pydata.org/en/latest/caching.html with respect to your problem.

**Comment by 22csnyder** [comment]
Matthew,

Hey thanks for the quick followup.

(1) just as an aside, it's not clear to me from the link whether dask
attempts to cache by default or not.

(2) I have an additional motivation to the caching which is specific to
dask.array and not addressed by the article. Lots of python modules work
with numpy already and they work great. (I use mayavi for volume rendering,
sklearn, skimage, etc). What I'd like to do (and maybe someone else too) is
pass these workflows an daskarray class that actually behaves like numpy,
but it sometimes takes longer when accessing elements.

Dask already does a *great *job at mirroring all of the np.ndarray style
and functionality. The difference is that skimage.imshow( daX[n] ) will not
work, but skimage.imshow(daX[n]) will.

A lot of the classes I build for visualization and image processing are
used to getting plain old np.ndarray's and dask.array's and should handle
both cleanly. My long-winded whiny motivation is that I started seeing

if hasattr(X,'dask'):
    do_something(X[a][b].compute())
elif isinstance(X,np.ndarray):
    do_something(X[a][b])

showing up several hundred times in my code. Now, note that you can call
do_something( np.array(X[a][b]) ) and it will behave the same in both
cases. But, (A) it's a little ugly considering how nice dask is; (B) it
won't save you if do_something() is a function that would like to return
dask or numpy arrays depending on what was given. e.g. slicing or getting a
patch around a point.

I guess realistically what I would like is for it to magically become a
numpy array when foo(X) fails but foo(X.compute()) doesn't, and when
efficient. e.g. I've already called X.compute().

(3) In my wildest dreams, you could use all of the functionality of sklearn
or any library that typically works on numpy arrays, just by passing a
dask.array, though it might take longer...


Sorry that was pretty ramble-y
Best,
Chris Snyder

**Comment by mrocklin** [comment]
(1) Opportunistic caching is not turned on by default.  You can turn it on as follows:

```python
from dask.cache import Cache
cache = Cache(2e9)
cache.register
```

(2) Trust me, I want exactly the same thing.  @shoyer is actually a good person on this because he's had to go through all of this pain when integrating `dask.array` into `xray`, which handles dask arrays and numpy ndarrays the same, depending on which was provided.  Stephan, do you have a writeup anywhere on your thoughts here or perhaps on duck arrays?

There are, as you point out, a few suboptimal solutions.

1. Use `np.asarray` whenever you know that the thing will have to turn into an `ndarray`.  Hopefully the upstream libraries, like `skimage` implement this within functions like `imshow`.  We'd like these calls to be as low down in the stack as possible (away from users.)
2. Don't do anything if the function only uses API that is strictly cared by both numpy and dask.array.
3. Find some way to try-except.

At the moment I'm mostly in favor of explicit calls to `np.asarray` when it's known to be necessary.  I don't think it's particularly ugly and it's pretty explicit.

The try-except idea is interesting.  Rules of Python don't let dask.arrays control this themselves (i.e. there is no `__rcall__` protocol) but one could imagine creating a decorator like the following:

```python
def try_dask(func):
    def new_func(*args, **kwargs):
        try:
            return func(*args, **kwargs)
        except:
            args = [np.asarray(arg) if hasattr(arg, '.dask') for arg in args]
            return func(*args, **kwargs)
    return new_func

@try_dask
def do_something(...)

do_something(maybe_dask_arrray)
```

**Comment by 22csnyder** [comment]
Yeah that's a clearer way of saying it. Okay seems we're all on the same
page..

(oooo xray looks interesting too!)

Just out of curiosity, (sorry off topic) do most of the people working on
dask work for Continuum Analytics, or is there a sizable volunteer core?

Best,
Chris Snyder

**Comment by mrocklin** [comment]
Most of the day-to-day grind (bugfixes, releases, etc.) is handled by people employed by Continuum of which there are between 1-3 of us at any given time.  

However yes, there is a sizable volunteer base.  Individuals here tend to focus on particular parts of dask that interest them.  @shoyer is active on dask.array. @sinhrks, a pandas dev, has probably done more work on dask.dataframe lately than any Continuum employee.  @marianotepper wrote all of `dask.array.linalg`, etc..  Generally speaking I'm very happy whenever anyone shows interest in taking on a component of dask.  If you are such a person then please help!

**Comment by 22csnyder** [comment]
Awesome. Yes I imagine I probably will at some point.

Best,
ChrisSnyder

**Comment by shoyer** [comment]
So, we actually have such a facade around dask.array in xray, though it's combined into our `xray.Variable` class, which also handles things like dimensions. Of course, this behavior is super useful -- for stuff that fits in memory, NumPy arrays can be significantly faster than dask. It might indeed be cleaner and independently useful to separate it out. So let me summarize how this aspect of the `xray.Variable` object works:
- `.data` can be either a dask array or a numpy array.
- `.values` is always a numpy array (this is similar to pandas, but actually slightly more strict)
- When `.values` is accessed, `.data` will be automatically computed if it's a dask array and replaced by the computed numpy array.
- When possible, we implement methods that work on both dask and numpy arrays (e.g., arithmetic, indexing or transpose) in terms of `.data`.
- For functions like `np.any` or `np.concatenate` that have equivalents in both xray and dask, I wrote my own wrapper module that uses `isinstance` checks to determine the right library to dispatch to (e.g., see [these lines in `xray.core.ops`](https://github.com/xray/xray/blob/6ea7eb2b388075cc838c5ddf0ddaa47020cfcb89/xray/core/ops.py#L52-L93)).

The transparent conversion and caching via `.values` works pretty well, though often it's not necessary because well written libraries already use `np.asarray` to wrap all input to their public APIs (as @mrocklin already mentioned).

My ad-hoc compatibility wrapper for functions is something that I would really, *really* like to see go away. Basically, the wrapper should exist in NumPy, though we'll need some serious discussions to figure out exactly what it should look like. There are a few possible solutions: either multiple dispatch or double-underscore methods like `__array_concatenate__` (I'm leaning towards the later). See here for some discussion: https://github.com/numpy/numpy/issues/4164

**Comment by datnamer** [comment]
@mrocklin @shoyer, not to hijack this thread too much...but there is some interesting feedback on your dasklean post that relates to this discussion: https://www.reddit.com/r/MachineLearning/comments/3pgx6y/dask_sklearn_experiment_reuse_intermediate/

**Comment by mrocklin** [comment]
Thanks for the pointer.  That's an interesting conversation.  You may find the dask gitter chat a good place to post things like this http://gitter.im/blaze/dask

**Comment by mrocklin** [comment]
Closing this as large-scope and stale.
