### ISSUE TITLE
Replace dill with cloudpickle

### ISSUE THREAD

**Issue by mrocklin** [blaze/dask#847]
Should we make this switch?  Cloudpickle handles a few pragmatic cases that dill does not, notably closures that include globals, e.g.

```python
>>> import numpy as np
>>> def f(x):
...     return np.sin(x) + np.cos(x)   # closed over np, a global
```

This  can be switched with the experimental `dill.settings['recurse'] = True` setting, but I've found that this causes some very strange behavior (functions like `int` are sometimes lost.)

 I've switched to `cloudpickle` in `distributed` and have so far been satisfied with the change.

**Comment by eribean** [comment]
This is beneficial for my projects, Im in favor of this change.

**Comment by PedroMDuarte** [comment]
@mrocklin  I started out by adding a test for something like the example you gave above: 

https://github.com/PedroMDuarte/dask/compare/fd5a8b88433b...e3ffdea46ce9

That test ran successfully in Travis (https://travis-ci.org/PedroMDuarte/dask/builds/94812034).   

Is there perhaps another way to expose the undesired behavior in dill?  Or maybe is the preference for cloudpickle based on performance but not functionality? 

@eribean Could you elaborate on a case where you would prefer cloudpickle rather than dill?

**Comment by mrocklin** [comment]
This will only happen when using dask interactively.

**Comment by mrocklin** [comment]
This commit from the `distributed` project might be helpful.  https://github.com/blaze/distributed/commit/6dc1f3f202fbef0e530b7e89c300e4f4d59dbc30

**Comment by cowlicks** [comment]
A user can still change the default serialization with `dask.set_options` right?

**Comment by mrocklin** [comment]
Yes

**Comment by mrocklin** [comment]
This happened.  Closing
